import React from 'react'
const accent = '#69dcff'
const lifecycle = [['APPROACH','Magnetic'],['CLARIFY','Intent'],['WEIGH','Ethical'],['COMMIT','Pressure'],['RESOLVE','Breathing'],['RECOVER','Reversible']]
const substitutions = [['Pressure','named stage controls'],['Hold','non-hold confirmation'],['Breathing motion','label and contrast'],['Magnetism','stable conventional target'],['Countdown','numeric time remaining']]
function Shell({ title, type, claim, displayMode, children, ctaLabel }) {
  if (displayMode === 'compact') return <article className='overflow-hidden rounded-[14px] border border-[#f7f1e7]/12 bg-[#0b0c0f] text-[#f7f1e7]'><div className='px-3.5 py-3'><div className='text-[8px] uppercase tracking-[0.16em] text-[#69dcff]'>{type}</div><h3 className='mt-2 text-[15px] leading-5'>{title}</h3><p className='mt-2 text-[10px] leading-4 text-[#f7f1e7]/52'>{claim}</p></div><div className='border-t border-[#f7f1e7]/12 px-3.5 py-2.5 text-[9px] uppercase tracking-[0.13em] text-[#f7f1e7]/52'>{ctaLabel}</div></article>
  return <article className='w-full bg-[#090a0d] text-[#f7f1e7]'><header className='border-b border-[#f7f1e7]/12 px-5 py-4'><div className='text-[9px] uppercase tracking-[0.16em] text-[#69dcff]'>{type}</div><h3 className='mt-2 text-[24px] tracking-[-0.03em]'>{title}</h3><p className='mt-2 max-w-[720px] text-[12px] leading-5 text-[#f7f1e7]/58'>{claim}</p></header><div className='p-5'>{children}</div><footer className='border-t border-[#f7f1e7]/12 px-5 py-3 text-[9px] uppercase tracking-[0.13em] text-[#f7f1e7]/34'>Interface Behavior Lab · implemented research artifact</footer></article>
}
export default function InterfaceBehaviorLabReceiptVisual(props) {
  const { title, type, claim, receiptBodyType, displayMode='full', ctaLabel='Inspect receipt' } = props
  let body
  if (receiptBodyType === 'lifecycle') body=<div className='grid gap-2 md:grid-cols-6'>{lifecycle.map(([stage,family],i)=><div key={stage} className='relative rounded-[16px] border border-[#f7f1e7]/12 bg-[#111318] p-3'><div className='font-mono text-[8px] text-[#f7f1e7]/32'>{String(i+1).padStart(2,'0')}</div><div className='mt-5 text-[9px] tracking-[0.14em] text-[#f7f1e7]/46'>{stage}</div><div className='mt-3 text-[15px]'>{family}</div><div className='mt-4 h-px bg-[#69dcff]/50'/></div>)}</div>
  else if (receiptBodyType === 'library') body=<div><div className='grid grid-cols-2 gap-2 md:grid-cols-4'>{[['95','variables'],['46','variants'],['6','families'],['3','modes']].map(([v,l])=><div key={l} className='rounded-[16px] border border-[#f7f1e7]/12 bg-[#111318] p-4'><div className='text-[30px] tracking-[-0.05em]' style={{color:accent}}>{v}</div><div className='mt-2 text-[9px] uppercase tracking-[0.14em] text-[#f7f1e7]/42'>{l}</div></div>)}</div><div className='mt-3 grid gap-2 md:grid-cols-4'>{['M + L sizes','text properties','boolean properties','semantic materials'].map(x=><div key={x} className='border-l border-[#69dcff]/55 pl-3 text-[11px] text-[#f7f1e7]/62'>{x}</div>)}</div></div>
  else if (receiptBodyType === 'accessibility') body=<div className='grid gap-5 md:grid-cols-[.75fr_1.25fr]'><div className='grid grid-cols-5 gap-1'>{['touch','pointer','gaze','voice','switch'].map(x=><div key={x} className='rounded-[12px] border border-[#f7f1e7]/12 bg-[#111318] px-2 py-4 text-center text-[8px] uppercase tracking-[0.1em] text-[#69dcff]'>{x}</div>)}</div><div className='divide-y divide-[#f7f1e7]/10'>{substitutions.map(([a,b])=><div key={a} className='grid grid-cols-[130px_1fr] gap-4 py-2.5 text-[11px]'><span>{a}</span><span className='text-[#f7f1e7]/48'>→ {b}</span></div>)}</div></div>
  else body=<div className='grid gap-4 md:grid-cols-[1.15fr_.85fr]'><div className='rounded-[18px] border border-[#f7f1e7]/12 bg-[#111318] p-4'><div className='flex flex-wrap gap-2'>{['Light','Dark','Spatial','Reduce Motion','Pointer','Voice','Switch'].map(x=><span key={x} className='rounded-full border border-[#f7f1e7]/12 px-2.5 py-1 text-[8px] text-[#f7f1e7]/52'>{x}</span>)}</div><div className='mt-8 rounded-full border border-[#69dcff]/45 bg-[#69dcff]/10 px-5 py-4'><div className='text-[13px]'>Continue with intent</div><div className='mt-1 text-[8px] tracking-[0.14em] text-[#f7f1e7]/42'>STATE · REVEALED</div></div></div><div className='rounded-[18px] border border-[#f7f1e7]/12 bg-[#111318] p-4'><div className='text-[8px] uppercase tracking-[0.14em] text-[#f7f1e7]/36'>Event log</div>{['Intent · revealed','Ethical · consequence shown','Reversible · undo opened'].map(x=><div key={x} className='mt-3 border-l border-[#69dcff]/45 pl-3 text-[10px] text-[#f7f1e7]/56'>{x}</div>)}</div></div>
  return <Shell title={title} type={type} claim={claim} displayMode={displayMode} ctaLabel={ctaLabel}>{body}</Shell>
}
